# FOOOF: Results Analysis

<div class="alert alert-success">
This tutorial explores some basic examples of analyzing the results from fitting FOOOF PSD models.
</div>

<div class="alert alert-info">
To go back to code-based examples of using FOOOF, go [here](02-FOOOF.ipynb).
</div>

## Exploring FOOOF analyses

FOOOF is really a way to extract features of interest from your data, features that can then be examined across or between groups of interest, or perhaps fed into further analysis. Largely, it is up to you what to do after running FOOOF. Here, we briefly introduce some analysis utilities that are packaged with FOOOF, and explore some simple analyses that can be done with FOOOF outputs. 

In [1]:
# Import FOOOFGroup
from fooof import FOOOF, FOOOFGroup

# FOOOF comes with some basic analysis function to work FOOOF outputs
from fooof.analysis import *

In [2]:
# Initialize a FOOOF object, and load data saved from previous tutorials
fm = FOOOF()
fm.load()

# Initialize a FOOOFGroup, and load data saved from the previous tutorials
fg = FOOOFGroup()
fg.load()

### FOOOF Analysis utilities

Note: currently FOOOF is packaged with minimal analysis utility functions. FOOOF is planned to stay this way, as supporting further analysis of FOOOF-derived results is largely outside the scope of the current module, and so we only directly include utility functions covering very general uses.

In [3]:
# Check out the docs for peak analyis helper function
get_band_peak?

### Analyzing band-specific oscillations

In [4]:
# Set up indexes for accessing data, for convenience
cf_ind, am_ind, bw_ind = 0, 1, 2

In [5]:
# Define alpha band
theta_band = [4, 8]
alpha_band = [8, 12]

In [6]:
# Extract any theta band oscillations from the FOOOF model
get_band_peak(fm.peak_params_, theta_band)

array([7.98920599, 0.82222326, 2.06407363])

The 'get_band_peak' function will extract peaks within a specified band from the results of a FOOOF fit. 

You can optionally specify whether to return all oscillations within that band, or a singular result, which returns the highest power peak (if there are multiple). 

In [7]:
# Get all alpha oscillations from a FOOOFGroup object
alphas = get_band_peak_group(fg.get_all_data('peak_params'), alpha_band, len(fg))

In [8]:
# Check out some of the alpha data
alphas[0:5, :]

array([[10.09964663,  0.47133132,  3.60705373],
       [10.08879109,  0.47731098,  3.68490876],
       [        nan,         nan,         nan],
       [10.09665833,  0.47097969,  3.6633977 ],
       [10.02854683,  0.48826778,  3.81333837]])

#### get_band_peak_group

Note that the design of 'get_band_peak_group' is such that it will retain information regarding which oscillation came from with model fit, such that each row corresponds to a specific model fit, such that the matrix returned is size [n_fits, 3].

In order to do so, at most 1 peak is extracted for each model fit within the specified band. If more than 1 peak are found within the band, the peak with the highest power is extracted. If no peaks are found within the specified band, that row is filled with 'nan'. 

In [9]:
# Check descriptive statistics of oscillation data
print('Alpha CF : ', np.nanmean(alphas[:, cf_ind]))
print('Alpha Amp: ', np.nanmean(alphas[:, am_ind]))
print('Alpha BW : ', np.nanmean(alphas[:, bw_ind]))

Alpha CF :  10.060683209051465
Alpha Amp:  0.48267528018942896
Alpha BW :  3.7307779968763746


### Analyzing aperiodic signal

In [10]:
# Extract slope data from group results
sls = fg.get_all_data('background_params', 'slope')

In [11]:
# Check out slope data
sls

array([2.03219939, 2.5261983 , 1.9998798 , 2.53002688, 1.51648434,
       1.50259231, 2.52335528, 2.01688269, 1.51448427, 2.52317579])

### Comparing across PSDs

Both of the examples above preserve information about which PSD particular features come from. If the PSDs come from across electrodes, channels or source reconstructed vertices, for example, extracting data in this way can be used to examine topographical relationships within and between these features. 

If your data comes from M/EEG, [MNE](https://github.com/mne-tools/mne-python) has visualization tools that you can use to, with a channel file, and a vector of FOOOF output data, visualzie FOOOF results across the scalp and/or cortex.

### Example FOOOF-related analyses

- Characterizing oscillation & 1/f, and analyzing spatial topographies, across demographics, modalities, and tasks
- Comparing oscillations within and between subjects across different tasks of interest
- Predicting disease state based on FOOOF derived oscillation & 1/f features
- Using FOOOF on a trial by trial manner to decode task properties, and behavioural states

<hr>
<div class="alert alert-success">
This is the end of the FOOOF tutorial materials!
</div>

<div class="alert alert-info">
If you are having any troubles, please submit an issue on Github [here](https://github.com/voytekresearch/fooof), and/or get in contact with us at voytekresearch@gmail.com.
</div>